global:
  scrape_interval: 15s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - ingestion:8011
          - miner:8012
          - analyzer:8013
          - writer:8014
          - query-api:8015
          - reporting:8016

  - job_name: dgraph
    static_configs:
      - targets:
          - dgraph:8080
